### ISSUE TITLE
Update geocode

### ISSUE THREAD

**Issue by bingalls** [geocoder-php/GeocoderLaravel#50] opened 2016-10-06 19:06 UTC
In short: GeocoderLaravel v0.6 uses an obsolete GuzzleHttp v3 library.
Details:
The latest stable "toin0u/geocoder-laravel": "^0.6.0" requires years-old "willdurand/geocoder" : "~2.4"
This old version of geocoder has an old Geocoder/HttpAdapter/GuzzleHttpAdapter.php that calls
use Guzzle\Service\Client;
This is old Guzzle 3.0 code
http://mtdowling.com/blog/2012/10/16/guzzle-3-dot-0-better-service-descriptions-and-more-modular/
Which, as explained in the current v6.x README.md is End Of Life.
This conflicts with other code, that runs a maintained version of GuzzleHttp lib.

Also note that the composer.json description field for "toin0u/geocoder-laravel": "^0.6.0" confusingly mentions Laravel v4, even though it requires
"illuminate/support"  : "~5.0"

This looks like it has been fixed in feature/update-for-laravel-5-3
If you could rename this branch with a dev- prefix, it would be accessible via Composer:
https://getcomposer.org/doc/05-repositories.md#loading-a-package-from-a-vcs-repository

**Comment by mikebronner** [comment] 2016-10-07 14:20
Hi @bingalls, we're working hard on getting this out sooner than later. You can access the feature branch in composer using the following syntax:
```
"require": {
  "toin0u/geocoder-laravel": "dev-feature/update-for-laravel-5-3@dev"
}
```

You may or may not need to add the `repositories` declaration:
```
"repositories": [
  {
    "type": "vcs",
    "url": "https://github.com/geocoder-php/GeocoderLaravel"
  }
],
```

Closing this, as this is really a duplicate of many other issues asking for the upgrade, and we're almost ready to release it.

If you do decide to use the feature branch, please let us know if you find any issues, that would be extremely helpful.

Thanks :)

**Closed** 2016-10-07 14:20 UTC
Labels: duplicate
